# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1923, 794)
        MainWindow.setStyleSheet("color:rgb(200,200,200);\n"
"background-color: rgb(20, 27, 45);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Cantarell")
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("/* ############ main tap widget ############# */\n"
"\n"
"QTabWidget::pane {\n"
"    border-top: 0px solid #C2C7CB;\n"
"}\n"
"QTabWidget::tab-bar {\n"
"    left: 0px; \n"
"}\n"
"QTabBar::tab {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"    border: 0px solid rgb(0, 0, 0);\n"
"    min-width: 53ex;\n"
"    padding: 09px;\n"
"}\n"
"#frame_54,QProgressBar,QLineEdit{\n"
"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.243781 rgba(62, 62, 62, 0));\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"    background:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.243781 rgba(62, 62, 62, 0));\n"
"\n"
"    border-bottom: 4px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 112, 187, 0), stop:0.263682 rgba(0, 112, 187, 255), stop:0.517413 rgba(0, 112, 187, 255), stop:0.766169 rgba(0, 112, 187, 255), stop:1 rgba(0, 112, 187, 0));\n"
"}\n"
"\n"
" \n"
"QTabBar::tab:selected {\n"
"    border-color:  qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 112, 187, 0), stop:0.189055 rgba(17, 0, 255, 255), stop:0.517413 rgba(17, 0, 255, 255), stop:0.81592 rgba(17, 0, 255, 255), stop:1 rgba(0, 112, 187, 0));\n"
"}\n"
"QTabBar::tab:!selected {\n"
"    margin-bottom: 4px; \n"
"}\n"
"QTabBar::tab:selected {\n"
"    margin-left: -4px;\n"
"    margin-right: -4px;\n"
"}\n"
"\n"
"\n"
"/* ####################### */\n"
"\n"
"QLabel,QCheckBox{\n"
"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.243781 rgba(62, 62, 62, 0));\n"
"}\n"
"\n"
"\n"
"QLineEdit , QPushButton , QToolButton , QListWidget , QListWidget::item , QPushButton , QSpinBox ,  QComboBox  , QDateEdit\n"
",#frame_7 ,#frame_9,QTextEdit,QProgressBar,#frame_29,#frame_49,#frame_40\n"
"{\n"
"padding-left:6px;\n"
"padding-right:6px;\n"
"\n"
"border: 1px solid rgb(48, 64, 99);;\n"
"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.243781 rgba(62, 62, 62, 0));\n"
"border-radius: 4px;\n"
"\n"
"}\n"
"\n"
"\n"
"QListWidget,#frame_29,#frame_49,#frame_40{\n"
"background-color: rgb(23, 31, 49);\n"
"\n"
"}\n"
"\n"
"#frame_7 ,#frame_9{\n"
"\n"
"    background-color:rgb(39, 53, 86);\n"
"}\n"
"\n"
"QPushButton , QToolButton,QLineEdit,QComboBox,QDateEdit\n"
",QSpinBox{border-radius: 10px;}\n"
"\n"
"\n"
"QComboBox::drop-down {\n"
"\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"}\n"
"\n"
"\n"
"QHeaderView::section:horizontal,QHeaderView::section:vertical{\n"
"background-color: rgb(17, 19, 36);}\n"
"\n"
"\n"
"QScrollBar::sub-page:vertical ,QScrollBar::add-page:vertical{\n"
"background:rgb(24, 32, 49);}\n"
"\n"
"\n"
"QToolButton:pressed,QPushButton:pressed,QListWidget:item {\n"
"padding:1px;\n"
"background-color: rgb(20, 27, 45);}\n"
"\n"
"\n"
"QListWidget {\n"
"padding-top:8px;\n"
"\n"
"}\n"
" QPushButton , QToolButton{\n"
"\n"
"padding:0px;\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:vertical,QListWidget:item:hover{\n"
"border-radius: 4px;\n"
"border: 2px solid rgb(164, 190, 217);\n"
"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.243781 rgba(62, 62, 62, 0));\n"
"}\n"
"\n"
"\n"
"\n"
"#mainFrame,QListWidget::item:selected {\n"
"    color: rgb(225, 225, 225);\n"
"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.243781 rgba(62, 62, 62, 0));\n"
"\n"
"border: 2px solid rgb(17, 0, 255);\n"
"\n"
"}\n"
"\n"
"#export_excel_but,#export_word_but,#import_excel_but,#presentation_but,#settings_but,#cards_but{\n"
"\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(48, 64, 99, 0), stop:0.572139 rgba(48, 64, 99, 0), stop:0.577114 rgba(24, 32, 49, 255), stop:1 rgba(24, 32, 49, 255));\n"
"\n"
"    padding: 0px;\n"
"    border: 1px solid rgb(75, 133, 196);\n"
"}\n"
"\n"
"\n"
"\n"
"QProgressBar{\n"
"border:0px;\n"
"padding:0px;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTableWidget{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"QHeaderView::section {\n"
"\n"
"    padding: 4px;\n"
"    color: rgb(255, 255, 255);\n"
"    border-style: none;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0));\n"
"\n"
"}\n"
"QHeaderView{\n"
"\n"
"    background-color:rgb(20, 27, 45);\n"
"\n"
"}\n"
"\n"
"\n"
"QTableView QTableCornerButton::section {\n"
"\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0));\n"
"\n"
"\n"
"}\n"
"QTableView {\n"
"color: rgb(255, 255, 255);\n"
" border: 0px ;\n"
"    background-color: rgb(20, 27, 45);\n"
"    border-width: 10px ;\n"
"    border-color: rgb(191, 200, 9);\n"
"    selection-background-color:rgb(77, 80, 143);\n"
"    selection-color: rgb(234, 255, 0);\n"
"}\n"
"\n"
"\n"
"\n"
"QToolTip{\n"
"color:rgb(210,210,210);\n"
"background-color:rgb(42, 58, 94);\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(48, 64, 99);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_3 = QtWidgets.QFrame(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.frame_3.setFont(font)
        self.frame_3.setStyleSheet("#frame_3  ,#frame{border:0px;}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setStyleSheet("#frame{\n"
"\n"
"    background-color: rgb(19, 23, 35);\n"
"border-radius: 10px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 0, 1, 1)
        self.product_name = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.product_name.setFont(font)
        self.product_name.setObjectName("product_name")
        self.gridLayout_4.addWidget(self.product_name, 1, 1, 1, 1)
        self.add_product = QtWidgets.QPushButton(self.frame)
        self.add_product.setMinimumSize(QtCore.QSize(49, 28))
        self.add_product.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.add_product.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_product.setIcon(icon)
        self.add_product.setObjectName("add_product")
        self.gridLayout_4.addWidget(self.add_product, 1, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 2, 0, 1, 1)
        self.matiral_type = QtWidgets.QComboBox(self.frame)
        self.matiral_type.setObjectName("matiral_type")
        self.gridLayout_4.addWidget(self.matiral_type, 2, 1, 1, 1)
        self.edit_product = QtWidgets.QPushButton(self.frame)
        self.edit_product.setMinimumSize(QtCore.QSize(49, 28))
        self.edit_product.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.edit_product.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.edit_product.setIcon(icon1)
        self.edit_product.setObjectName("edit_product")
        self.gridLayout_4.addWidget(self.edit_product, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 3, 0, 1, 1)
        self.product_code = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.product_code.setFont(font)
        self.product_code.setObjectName("product_code")
        self.gridLayout_4.addWidget(self.product_code, 3, 1, 1, 1)
        self.delete_product = QtWidgets.QPushButton(self.frame)
        self.delete_product.setMinimumSize(QtCore.QSize(69, 28))
        self.delete_product.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.delete_product.setFont(font)
        self.delete_product.setStyleSheet("border-color:rgb(161, 0, 0);\n"
"border-width:2px; ")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_product.setIcon(icon2)
        self.delete_product.setObjectName("delete_product")
        self.gridLayout_4.addWidget(self.delete_product, 3, 2, 1, 1)
        self.products_list = QtWidgets.QListWidget(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.products_list.setFont(font)
        self.products_list.setObjectName("products_list")
        self.gridLayout_4.addWidget(self.products_list, 4, 0, 1, 3)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 3)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        self.units_frame = QtWidgets.QFrame(self.frame_3)
        self.units_frame.setEnabled(True)
        self.units_frame.setMinimumSize(QtCore.QSize(0, 107))
        self.units_frame.setStyleSheet("#units_frame{\n"
"border: 1px solid rgb(19, 23, 35);;\n"
"\n"
"border-radius: 4px;\n"
"}")
        self.units_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.units_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.units_frame.setObjectName("units_frame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.units_frame)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.unit_value = QtWidgets.QDoubleSpinBox(self.units_frame)
        self.unit_value.setStyleSheet("border:0px;\n"
"")
        self.unit_value.setAlignment(QtCore.Qt.AlignCenter)
        self.unit_value.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.unit_value.setMaximum(1e+19)
        self.unit_value.setObjectName("unit_value")
        self.gridLayout_6.addWidget(self.unit_value, 3, 1, 1, 1)
        self.units_list = QtWidgets.QListWidget(self.units_frame)
        self.units_list.setObjectName("units_list")
        self.gridLayout_6.addWidget(self.units_list, 4, 0, 1, 5)
        self.label_6 = QtWidgets.QLabel(self.units_frame)
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("border:0px;")
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 0, 1, 1, 1)
        self.delete_unit = QtWidgets.QPushButton(self.units_frame)
        self.delete_unit.setMinimumSize(QtCore.QSize(67, 27))
        self.delete_unit.setMaximumSize(QtCore.QSize(67, 27))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.delete_unit.setFont(font)
        self.delete_unit.setStyleSheet("border-color:rgb(161, 0, 0);\n"
"border-width:2px; ")
        self.delete_unit.setIcon(icon2)
        self.delete_unit.setObjectName("delete_unit")
        self.gridLayout_6.addWidget(self.delete_unit, 1, 4, 1, 1)
        self.add_unit = QtWidgets.QPushButton(self.units_frame)
        self.add_unit.setMinimumSize(QtCore.QSize(67, 27))
        self.add_unit.setMaximumSize(QtCore.QSize(67, 27))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.add_unit.setFont(font)
        self.add_unit.setIcon(icon)
        self.add_unit.setObjectName("add_unit")
        self.gridLayout_6.addWidget(self.add_unit, 1, 2, 1, 1)
        self.unit_name = QtWidgets.QLineEdit(self.units_frame)
        self.unit_name.setObjectName("unit_name")
        self.gridLayout_6.addWidget(self.unit_name, 2, 1, 1, 4)
        self.label_7 = QtWidgets.QLabel(self.units_frame)
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.units_frame)
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_6.addWidget(self.label_9, 2, 0, 1, 1)
        self.edit_unit = QtWidgets.QPushButton(self.units_frame)
        self.edit_unit.setMinimumSize(QtCore.QSize(67, 27))
        self.edit_unit.setMaximumSize(QtCore.QSize(67, 27))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.edit_unit.setFont(font)
        self.edit_unit.setIcon(icon1)
        self.edit_unit.setObjectName("edit_unit")
        self.gridLayout_6.addWidget(self.edit_unit, 1, 3, 1, 1)
        self.units_combo = QtWidgets.QComboBox(self.units_frame)
        self.units_combo.setObjectName("units_combo")
        self.gridLayout_6.addWidget(self.units_combo, 3, 2, 1, 3)
        self.gridLayout_2.addWidget(self.units_frame, 0, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setStyleSheet("#frame_2{\n"
"\n"
"    background-color: rgb(19, 23, 35);\n"
"border-radius: 10px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_9.addWidget(self.label_5, 1, 0, 1, 1)
        self.material_name = QtWidgets.QLineEdit(self.frame_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.material_name.setFont(font)
        self.material_name.setObjectName("material_name")
        self.gridLayout_9.addWidget(self.material_name, 1, 1, 1, 2)
        self.add_rm = QtWidgets.QPushButton(self.frame_2)
        self.add_rm.setMinimumSize(QtCore.QSize(49, 28))
        self.add_rm.setMaximumSize(QtCore.QSize(69, 28))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.add_rm.setFont(font)
        self.add_rm.setIcon(icon)
        self.add_rm.setObjectName("add_rm")
        self.gridLayout_9.addWidget(self.add_rm, 1, 3, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_9.addWidget(self.label_17, 2, 0, 1, 1)
        self.r_matiral_type = QtWidgets.QComboBox(self.frame_2)
        self.r_matiral_type.setObjectName("r_matiral_type")
        self.gridLayout_9.addWidget(self.r_matiral_type, 2, 1, 1, 2)
        self.edit_rm = QtWidgets.QPushButton(self.frame_2)
        self.edit_rm.setMinimumSize(QtCore.QSize(49, 28))
        self.edit_rm.setMaximumSize(QtCore.QSize(69, 28))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.edit_rm.setFont(font)
        self.edit_rm.setIcon(icon1)
        self.edit_rm.setObjectName("edit_rm")
        self.gridLayout_9.addWidget(self.edit_rm, 2, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_9.addWidget(self.label_4, 3, 0, 1, 1)
        self.material_code = QtWidgets.QLineEdit(self.frame_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.material_code.setFont(font)
        self.material_code.setObjectName("material_code")
        self.gridLayout_9.addWidget(self.material_code, 3, 1, 1, 2)
        self.delete_rm = QtWidgets.QPushButton(self.frame_2)
        self.delete_rm.setMinimumSize(QtCore.QSize(69, 28))
        self.delete_rm.setMaximumSize(QtCore.QSize(69, 28))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.delete_rm.setFont(font)
        self.delete_rm.setStyleSheet("border-color:rgb(161, 0, 0);\n"
"border-width:2px; ")
        self.delete_rm.setIcon(icon2)
        self.delete_rm.setObjectName("delete_rm")
        self.gridLayout_9.addWidget(self.delete_rm, 3, 3, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_9.addWidget(self.label_19, 4, 0, 1, 1)
        self.rm_quantity = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.rm_quantity.setStyleSheet("border:0px;\n"
"background-color: rgb(19, 23, 35);")
        self.rm_quantity.setAlignment(QtCore.Qt.AlignCenter)
        self.rm_quantity.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.rm_quantity.setMaximum(1e+19)
        self.rm_quantity.setObjectName("rm_quantity")
        self.gridLayout_9.addWidget(self.rm_quantity, 4, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.rm_units_combo = QtWidgets.QComboBox(self.frame_2)
        self.rm_units_combo.setObjectName("rm_units_combo")
        self.gridLayout_9.addWidget(self.rm_units_combo, 4, 2, 1, 2)
        self.rm_list = QtWidgets.QListWidget(self.frame_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rm_list.setFont(font)
        self.rm_list.setObjectName("rm_list")
        self.gridLayout_9.addWidget(self.rm_list, 5, 0, 1, 4)
        self.label_18 = QtWidgets.QLabel(self.frame_2)
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout_9.addWidget(self.label_18, 0, 0, 1, 4)
        self.gridLayout_2.addWidget(self.frame_2, 1, 0, 1, 1)
        self.rm_frame = QtWidgets.QFrame(self.frame_3)
        self.rm_frame.setEnabled(True)
        self.rm_frame.setMinimumSize(QtCore.QSize(0, 107))
        self.rm_frame.setStyleSheet("#rm_frame{\n"
"border: 1px solid rgb(19, 23, 35);;\n"
"\n"
"border-radius: 4px;}")
        self.rm_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.rm_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rm_frame.setObjectName("rm_frame")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.rm_frame)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_12 = QtWidgets.QLabel(self.rm_frame)
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_8.addWidget(self.label_12, 2, 0, 1, 1)
        self.add_p_rm = QtWidgets.QPushButton(self.rm_frame)
        self.add_p_rm.setMinimumSize(QtCore.QSize(67, 27))
        self.add_p_rm.setMaximumSize(QtCore.QSize(67, 27))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.add_p_rm.setFont(font)
        self.add_p_rm.setIcon(icon)
        self.add_p_rm.setObjectName("add_p_rm")
        self.gridLayout_8.addWidget(self.add_p_rm, 1, 4, 1, 1)
        self.p_rm_combo = QtWidgets.QComboBox(self.rm_frame)
        self.p_rm_combo.setObjectName("p_rm_combo")
        self.p_rm_combo.addItem("")
        self.p_rm_combo.addItem("")
        self.p_rm_combo.addItem("")
        self.p_rm_combo.addItem("")
        self.p_rm_combo.addItem("")
        self.gridLayout_8.addWidget(self.p_rm_combo, 2, 1, 1, 6)
        self.label_11 = QtWidgets.QLabel(self.rm_frame)
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_8.addWidget(self.label_11, 3, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.rm_frame)
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("border:0px;")
        self.label_10.setObjectName("label_10")
        self.gridLayout_8.addWidget(self.label_10, 0, 0, 1, 7)
        self.p_rm_list = QtWidgets.QListWidget(self.rm_frame)
        self.p_rm_list.setObjectName("p_rm_list")
        self.gridLayout_8.addWidget(self.p_rm_list, 5, 0, 1, 7)
        self.delete_p_rm = QtWidgets.QPushButton(self.rm_frame)
        self.delete_p_rm.setMinimumSize(QtCore.QSize(67, 27))
        self.delete_p_rm.setMaximumSize(QtCore.QSize(67, 27))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.delete_p_rm.setFont(font)
        self.delete_p_rm.setStyleSheet("border-color:rgb(161, 0, 0);\n"
"border-width:2px; ")
        self.delete_p_rm.setIcon(icon2)
        self.delete_p_rm.setObjectName("delete_p_rm")
        self.gridLayout_8.addWidget(self.delete_p_rm, 1, 6, 1, 1)
        self.edit_p_rm = QtWidgets.QPushButton(self.rm_frame)
        self.edit_p_rm.setMinimumSize(QtCore.QSize(67, 27))
        self.edit_p_rm.setMaximumSize(QtCore.QSize(67, 27))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.edit_p_rm.setFont(font)
        self.edit_p_rm.setIcon(icon1)
        self.edit_p_rm.setObjectName("edit_p_rm")
        self.gridLayout_8.addWidget(self.edit_p_rm, 1, 5, 1, 1)
        self.p_rm_m_unit = QtWidgets.QComboBox(self.rm_frame)
        self.p_rm_m_unit.setObjectName("p_rm_m_unit")
        self.gridLayout_8.addWidget(self.p_rm_m_unit, 3, 5, 1, 2)
        self.p_rm_m_quantity = QtWidgets.QDoubleSpinBox(self.rm_frame)
        self.p_rm_m_quantity.setStyleSheet("border:0px; \n"
"")
        self.p_rm_m_quantity.setAlignment(QtCore.Qt.AlignCenter)
        self.p_rm_m_quantity.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.p_rm_m_quantity.setMaximum(1e+19)
        self.p_rm_m_quantity.setObjectName("p_rm_m_quantity")
        self.gridLayout_8.addWidget(self.p_rm_m_quantity, 3, 4, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.rm_frame)
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_8.addWidget(self.label_13, 3, 3, 1, 1)
        self.p_rm_t_unit = QtWidgets.QComboBox(self.rm_frame)
        self.p_rm_t_unit.setObjectName("p_rm_t_unit")
        self.gridLayout_8.addWidget(self.p_rm_t_unit, 3, 2, 1, 1)
        self.p_rm_t_quantity = QtWidgets.QDoubleSpinBox(self.rm_frame)
        self.p_rm_t_quantity.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.p_rm_t_quantity.setMaximum(1e+19)
        self.p_rm_t_quantity.setObjectName("p_rm_t_quantity")
        self.gridLayout_8.addWidget(self.p_rm_t_quantity, 3, 1, 1, 1)
        self.gridLayout_2.addWidget(self.rm_frame, 1, 1, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setEnabled(True)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 107))
        self.frame_4.setStyleSheet("#frame_4{border: 1px solid rgb(19, 23, 35);;\n"
"\n"
"border-radius: 4px;}\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.delete_order = QtWidgets.QPushButton(self.frame_4)
        self.delete_order.setMinimumSize(QtCore.QSize(67, 27))
        self.delete_order.setMaximumSize(QtCore.QSize(67, 27))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.delete_order.setFont(font)
        self.delete_order.setStyleSheet("border-color:rgb(161, 0, 0);\n"
"border-width:2px; ")
        self.delete_order.setIcon(icon2)
        self.delete_order.setObjectName("delete_order")
        self.gridLayout_7.addWidget(self.delete_order, 1, 5, 1, 1)
        self.add_order = QtWidgets.QPushButton(self.frame_4)
        self.add_order.setMinimumSize(QtCore.QSize(67, 27))
        self.add_order.setMaximumSize(QtCore.QSize(67, 27))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.add_order.setFont(font)
        self.add_order.setIcon(icon)
        self.add_order.setObjectName("add_order")
        self.gridLayout_7.addWidget(self.add_order, 1, 3, 1, 1)
        self.edit_order = QtWidgets.QPushButton(self.frame_4)
        self.edit_order.setMinimumSize(QtCore.QSize(67, 27))
        self.edit_order.setMaximumSize(QtCore.QSize(67, 27))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.edit_order.setFont(font)
        self.edit_order.setIcon(icon1)
        self.edit_order.setObjectName("edit_order")
        self.gridLayout_7.addWidget(self.edit_order, 1, 4, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.frame_4)
        self.label_21.setObjectName("label_21")
        self.gridLayout_7.addWidget(self.label_21, 4, 3, 1, 1)
        self.order_name = QtWidgets.QLineEdit(self.frame_4)
        self.order_name.setObjectName("order_name")
        self.gridLayout_7.addWidget(self.order_name, 2, 1, 1, 5)
        self.orders_list = QtWidgets.QListWidget(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Cantarell Thin")
        font.setPointSize(13)
        self.orders_list.setFont(font)
        self.orders_list.setStyleSheet("")
        self.orders_list.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.orders_list.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.orders_list.setObjectName("orders_list")
        self.gridLayout_7.addWidget(self.orders_list, 6, 0, 1, 6)
        self.label_20 = QtWidgets.QLabel(self.frame_4)
        self.label_20.setObjectName("label_20")
        self.gridLayout_7.addWidget(self.label_20, 5, 3, 1, 1)
        self.order_unit = QtWidgets.QComboBox(self.frame_4)
        self.order_unit.setObjectName("order_unit")
        self.gridLayout_7.addWidget(self.order_unit, 3, 3, 1, 3)
        self.date_order_from = QtWidgets.QDateEdit(self.frame_4)
        self.date_order_from.setStyleSheet("  QCalendarWidget QWidget { \n"
"background-color: rgb(20, 27, 45);\n"
"\n"
"border: 0px solid rgb(48, 64, 99);;\n"
"border-radius: 0px;\n"
"\n"
"\n"
"}\n"
"\n"
"QCalendarWidget QAbstractItemView:disabled \n"
"{ \n"
"color: rgb(179, 179, 179); \n"
"}\n"
"  QCalendarWidget QWidget { alternate-background-color: rgb(28, 61, 135); }\n"
"\n"
"QDateEdit::drop-down {\n"
"    image: url(:/new/myapp/cbarrowdn.png);\n"
"border: 1px solid rgb(164, 190, 217);\n"
"    border-bottom-right-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"}")
        self.date_order_from.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.date_order_from.setCalendarPopup(True)
        self.date_order_from.setObjectName("date_order_from")
        self.gridLayout_7.addWidget(self.date_order_from, 4, 4, 1, 2)
        self.order_done = QtWidgets.QCheckBox(self.frame_4)
        self.order_done.setObjectName("order_done")
        self.gridLayout_7.addWidget(self.order_done, 1, 0, 1, 1)
        self.date_order_to = QtWidgets.QDateEdit(self.frame_4)
        self.date_order_to.setStyleSheet("  QCalendarWidget QWidget { \n"
"background-color: rgb(20, 27, 45);\n"
"\n"
"border: 0px solid rgb(48, 64, 99);;\n"
"border-radius: 0px;\n"
"\n"
"\n"
"}\n"
"\n"
"QCalendarWidget QAbstractItemView:disabled \n"
"{ \n"
"color: rgb(179, 179, 179); \n"
"}\n"
"  QCalendarWidget QWidget { alternate-background-color: rgb(28, 61, 135); }\n"
"\n"
"QDateEdit::drop-down {\n"
"    image: url(:/new/myapp/cbarrowdn.png);\n"
"border: 1px solid rgb(164, 190, 217);\n"
"    border-bottom-right-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"}")
        self.date_order_to.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.date_order_to.setCalendarPopup(True)
        self.date_order_to.setTimeSpec(QtCore.Qt.LocalTime)
        self.date_order_to.setDate(QtCore.QDate(2020, 1, 1))
        self.date_order_to.setObjectName("date_order_to")
        self.gridLayout_7.addWidget(self.date_order_to, 5, 4, 1, 2)
        self.label_14 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("border:0px;")
        self.label_14.setObjectName("label_14")
        self.gridLayout_7.addWidget(self.label_14, 0, 0, 1, 6)
        self.label_15 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_7.addWidget(self.label_15, 2, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout_7.addWidget(self.label_16, 3, 0, 1, 1)
        self.order_color = QtWidgets.QComboBox(self.frame_4)
        self.order_color.setMaximumSize(QtCore.QSize(53, 23))
        self.order_color.setObjectName("order_color")
        self.gridLayout_7.addWidget(self.order_color, 1, 2, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.frame_4)
        self.label_22.setObjectName("label_22")
        self.gridLayout_7.addWidget(self.label_22, 1, 1, 1, 1)
        self.order_quantity = QtWidgets.QDoubleSpinBox(self.frame_4)
        self.order_quantity.setStyleSheet("border:0px;\n"
"")
        self.order_quantity.setAlignment(QtCore.Qt.AlignCenter)
        self.order_quantity.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.order_quantity.setMaximum(1e+19)
        self.order_quantity.setObjectName("order_quantity")
        self.gridLayout_7.addWidget(self.order_quantity, 3, 1, 1, 2)
        self.gridLayout_2.addWidget(self.frame_4, 0, 2, 2, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.gridLayout_2.setColumnStretch(2, 1)
        self.gridLayout_3.addWidget(self.frame_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.all_orders = QtWidgets.QTableWidget(self.tab_3)
        self.all_orders.setObjectName("all_orders")
        self.all_orders.setColumnCount(1)
        self.all_orders.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.all_orders.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.all_orders.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(221, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.all_orders.setItem(0, 0, item)
        self.gridLayout_5.addWidget(self.all_orders, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.order_color.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.product_name, self.matiral_type)
        MainWindow.setTabOrder(self.matiral_type, self.product_code)
        MainWindow.setTabOrder(self.product_code, self.add_product)
        MainWindow.setTabOrder(self.add_product, self.edit_product)
        MainWindow.setTabOrder(self.edit_product, self.delete_product)
        MainWindow.setTabOrder(self.delete_product, self.products_list)
        MainWindow.setTabOrder(self.products_list, self.material_name)
        MainWindow.setTabOrder(self.material_name, self.r_matiral_type)
        MainWindow.setTabOrder(self.r_matiral_type, self.material_code)
        MainWindow.setTabOrder(self.material_code, self.rm_quantity)
        MainWindow.setTabOrder(self.rm_quantity, self.rm_units_combo)
        MainWindow.setTabOrder(self.rm_units_combo, self.add_rm)
        MainWindow.setTabOrder(self.add_rm, self.edit_rm)
        MainWindow.setTabOrder(self.edit_rm, self.delete_rm)
        MainWindow.setTabOrder(self.delete_rm, self.rm_list)
        MainWindow.setTabOrder(self.rm_list, self.unit_name)
        MainWindow.setTabOrder(self.unit_name, self.unit_value)
        MainWindow.setTabOrder(self.unit_value, self.units_combo)
        MainWindow.setTabOrder(self.units_combo, self.add_unit)
        MainWindow.setTabOrder(self.add_unit, self.edit_unit)
        MainWindow.setTabOrder(self.edit_unit, self.delete_unit)
        MainWindow.setTabOrder(self.delete_unit, self.units_list)
        MainWindow.setTabOrder(self.units_list, self.p_rm_combo)
        MainWindow.setTabOrder(self.p_rm_combo, self.p_rm_t_quantity)
        MainWindow.setTabOrder(self.p_rm_t_quantity, self.p_rm_t_unit)
        MainWindow.setTabOrder(self.p_rm_t_unit, self.p_rm_m_quantity)
        MainWindow.setTabOrder(self.p_rm_m_quantity, self.p_rm_m_unit)
        MainWindow.setTabOrder(self.p_rm_m_unit, self.add_p_rm)
        MainWindow.setTabOrder(self.add_p_rm, self.edit_p_rm)
        MainWindow.setTabOrder(self.edit_p_rm, self.delete_p_rm)
        MainWindow.setTabOrder(self.delete_p_rm, self.p_rm_list)
        MainWindow.setTabOrder(self.p_rm_list, self.order_done)
        MainWindow.setTabOrder(self.order_done, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.order_name)
        MainWindow.setTabOrder(self.order_name, self.order_quantity)
        MainWindow.setTabOrder(self.order_quantity, self.order_unit)
        MainWindow.setTabOrder(self.order_unit, self.date_order_from)
        MainWindow.setTabOrder(self.date_order_from, self.date_order_to)
        MainWindow.setTabOrder(self.date_order_to, self.order_color)
        MainWindow.setTabOrder(self.order_color, self.add_order)
        MainWindow.setTabOrder(self.add_order, self.edit_order)
        MainWindow.setTabOrder(self.edit_order, self.delete_order)
        MainWindow.setTabOrder(self.delete_order, self.orders_list)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Product Name :</p></body></html>"))
        self.add_product.setText(_translate("MainWindow", "Add"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-weight:600;\">Matiral Types :</span></p></body></html>"))
        self.edit_product.setText(_translate("MainWindow", "Edit"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Code :</p></body></html>"))
        self.delete_product.setText(_translate("MainWindow", "Del"))
        self.products_list.setSortingEnabled(True)
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Products</p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Measuring Units</span></p></body></html>"))
        self.delete_unit.setText(_translate("MainWindow", "Del"))
        self.add_unit.setText(_translate("MainWindow", "Add"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Value :</p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-weight:600;\">Unit Name :</span></p></body></html>"))
        self.edit_unit.setText(_translate("MainWindow", "Edit"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Material Name :</p></body></html>"))
        self.add_rm.setText(_translate("MainWindow", "add"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-weight:600;\">Matiral Types :</span></p></body></html>"))
        self.edit_rm.setText(_translate("MainWindow", "Edit"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Code :</p></body></html>"))
        self.delete_rm.setText(_translate("MainWindow", "Del"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Available Quantity :</span></p></body></html>"))
        self.rm_list.setSortingEnabled(True)
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Raw Materials</p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-weight:600;\">Material :</span></p></body></html>"))
        self.add_p_rm.setText(_translate("MainWindow", "Add"))
        self.p_rm_combo.setItemText(0, _translate("MainWindow", "New Item"))
        self.p_rm_combo.setItemText(1, _translate("MainWindow", "1"))
        self.p_rm_combo.setItemText(2, _translate("MainWindow", "2"))
        self.p_rm_combo.setItemText(3, _translate("MainWindow", "3"))
        self.p_rm_combo.setItemText(4, _translate("MainWindow", "4"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Every :</p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Product Raw Materials</span></p></body></html>"))
        self.delete_p_rm.setText(_translate("MainWindow", "Del"))
        self.edit_p_rm.setText(_translate("MainWindow", "Edit "))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">have</p></body></html>"))
        self.p_rm_t_quantity.setStyleSheet(_translate("MainWindow", "border:0px; \n"
""))
        self.delete_order.setText(_translate("MainWindow", "Del"))
        self.add_order.setText(_translate("MainWindow", "Add"))
        self.edit_order.setText(_translate("MainWindow", "Edit"))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">From :</p></body></html>"))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">To :</p></body></html>"))
        self.date_order_from.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy"))
        self.order_done.setText(_translate("MainWindow", "Done"))
        self.date_order_to.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Orders</p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Order Name :</p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Quantity :</p></body></html>"))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Order color :</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Final Products"))
        item = self.all_orders.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.all_orders.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        __sortingEnabled = self.all_orders.isSortingEnabled()
        self.all_orders.setSortingEnabled(False)
        self.all_orders.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Action Plan"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
